[package]
name = "ecad_compare"
authors.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true
include.workspace = true


[dependencies]
ecad_file_format = { path = "../ecad_file_format" }
anyhow = "1.0"