[package]
name = "generate_netlists"
authors.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true
include.workspace = true

[dependencies]
sha2 = "0.10"
hex = "0.4"
subprocess = "0.2"